version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: snippetbox
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
